name: todolist
description: "Minimalist task manager with Stoic philosophy and Roman aesthetics."
publish_to: 'none'

# Версия будет обновляться скриптом
version: 1.0.11+11

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # База данных
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Утилиты
  intl: ^0.20.2 
  uuid: ^4.2.1
  path_provider: ^2.1.1
  package_info_plus: ^8.0.0  # <-- ДОБАВИЛ ДЛЯ ОТОБРАЖЕНИЯ ВЕРСИИ
  
  # UI и иконки
  cupertino_icons: ^1.0.2
  
  # Обновления (RuStore)
  flutter_rustore_update: ^10.0.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true